uint8 UNKNOWN_CLASS = 0
uint8 EMG = 1
uint8 ECG = 2
uint8 LIGHT = 3
uint8 EDA = 4
uint8 BVP = 5
uint8 RESP = 6
uint8 XYZ = 7
uint8 SYNC = 8
uint8 EEG = 9
uint8 SYNC_ADAP = 10
uint8 SYNC_LED = 11
uint8 SYNC_SW = 12
uint8 USB = 13
uint8 FORCE = 14
uint8 TEMP = 15
uint8 VPROBE = 16
uint8 BREAKOUT = 17
uint8 OXIMETER = 18
uint8 GONI = 19
uint8 ACT = 20
uint8 EOG = 21
uint8 EGG = 22
uint8 ANSA = 23
uint8 OSL = 26

uint8 sensor_type
uint8 port
float32 value